{
    '_stale': True,
    'stale_callback': < function _stale_figure_callback at 0x11ca6f240 > ,
    '_axes': < Axes: > ,
    'figure': < Figure size 640 x480 with 1 Axes > ,
    '_transform': None,
    '_transformSet': False,
    '_visible': True,
    '_animated': False,
    '_alpha': None,
    'clipbox': None,
    '_clippath': None,
    '_clipon': True,
    '_label': '',
    '_picker': None,
    '_rasterized': False,
    '_agg_filter': None,
    '_mouseover': False,
    '_callbacks': < matplotlib.cbook.CallbackRegistry object at 0x11d9d3dd0 > ,
    '_remove_method': < bound method FigureBase.delaxes of < Figure size 640 x480 with 1 Axes >> ,
    '_url': None,
    '_gid': None,
    '_snap': None,
    '_sketch': None,
    '_path_effects': [],
    '_sticky_edges': _XYPair(x = [], y = []),
    '_in_layout': True,
    '_position': Bbox([
        [0.125, 0.09999999999999998],
        [0.9, 0.9]
    ]),
    '_originalPosition': Bbox([
        [0.125, 0.09999999999999998],
        [0.9, 0.9]
    ]),
    '_aspect': 'auto',
    '_adjustable': 'box',
    '_anchor': 'C',
    '_stale_viewlims': {
        'x': True,
        'y': True
    },
    '_sharex': None,
    '_sharey': None,
    'bbox': < matplotlib.transforms.TransformedBbox object at 0x11da3b210 > ,
    'dataLim': Bbox([
        [0.0, 0.0],
        [99.0, 9801.0]
    ]),
    '_viewLim': Bbox([
        [-0.06, -0.06],
        [0.06, 0.06]
    ]),
    'transScale': < matplotlib.transforms.TransformWrapper object at 0x11da3b690 > ,
    'transAxes': < matplotlib.transforms.BboxTransformTo object at 0x106b6aa90 > ,
    'transLimits': < matplotlib.transforms.BboxTransformFrom object at 0x11d9d69d0 > ,
    'transData': < matplotlib.transforms.CompositeGenericTransform object at 0x11cfcf7d0 > ,
    '_xaxis_transform': < matplotlib.transforms.BlendedGenericTransform object at 0x11da3b4d0 > ,
    '_yaxis_transform': < matplotlib.transforms.BlendedGenericTransform object at 0x11da24a10 > ,
    '_subplotspec': GridSpec(1, 1)[0: 1, 0: 1],
    '_box_aspect': None,
    '_axes_locator': None,
    '_children': [ < matplotlib.collections.PathCollection object at 0x11da49ad0 > ],
    '_colorbars': [],
    'spines': < matplotlib.spines.Spines object at 0x11d980750 > ,
    'xaxis': < matplotlib.axis.XAxis object at 0x11ca1dad0 > ,
    'yaxis': < matplotlib.axis.YAxis object at 0x11d938450 > ,
    '_facecolor': 'w',
    '_frameon': True,
    '_axisbelow': False,
    '_rasterization_zorder': None,
    'ignore_existing_data_limits': False,
    'callbacks': < matplotlib.cbook.CallbackRegistry object at 0x11caa6e90 > ,
    '_xmargin': 0.05,
    '_ymargin': 0.05,
    '_tight': None,
    '_use_sticky_edges': True,
    '_get_lines': < matplotlib.axes._base._process_plot_var_args object at 0x11d96e910 > ,
    '_get_patches_for_fill': < matplotlib.axes._base._process_plot_var_args object at 0x11da49e50 > ,
    '_gridOn': False,
    '_mouseover_set': < matplotlib.cbook._OrderedSet object at 0x11da64250 > ,
    'child_axes': [],
    '_current_image': None,
    '_projection_init': ( < class 'matplotlib.axes._axes.Axes' > , {
        'sharex': None,
        'sharey': None
    }),
    'legend_': None,
    'containers': [],
    '_autotitlepos': False,
    'title': Text(0.5, 1.0, ''),
    '_left_title': Text(0.0, 1.0, ''),
    '_right_title': Text(1.0, 1.0, ''),
    'titleOffsetTrans': < matplotlib.transforms.ScaledTranslation object at 0x11da1dc90 > ,
    'patch': < matplotlib.patches.Rectangle object at 0x11da68b10 > ,
    'axison': True,
    'fmt_xdata': None,
    'fmt_ydata': None,
    '_navigate': True,
    '_navigate_mode': None
}